#ifndef LIKE2048LOGIC_GLOBAL_HPP
#define LIKE2048LOGIC_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(LIKE2048LOGIC_LIBRARY)
#  define LIKE2048LOGICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIKE2048LOGICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIKE2048LOGIC_GLOBAL_HPP
