#ifndef LIKE2048LOGIC_GLOBAL_HPP
#define LIKE2048LOGIC_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(LOGIC_LIBRARY)
#  define LOGICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIKE2048LOGIC_GLOBAL_HPP
